type Application = {
  _id: string;
  jobid: string;
  jobname: string;
  applicantid: string;
  applicantname: string;
  applicantemail: string;
  applicantSkills: string;
  phonenumber: string;
  manageremail: string;
  managerAffilication: string;
  managername: string;
  address: string;
  hours: string;
  dob: string;
  rating: string;
  gender: string;
  skills: string;
  status: string;
  answer1: string;
  answer2: string;
  answer3: string;
  answer4: string;
};
